CREATE TABLE CAR(
CAR_NO INT,
CAR_NAME VARCHAR(40),
CAR_PRICE INT,
CAR_QUALITY INT);

INSERT INTO CAR VALUES(112,"TESLA",120000,2),
(113,"BMW",230000,3),
(114,"AUDI",250000,4),
(116,"TATA",120000,5),
(119,"KIA",230000,4);

SELECT * FROM CAR;

SELECT COUNT(CAR_NAME),CAR_PRICE FROM CAR GROUP BY CAR_PRICE;

SELECT COUNT(CAR_NAME) AS COUNT_NUMBER,CAR_PRICE FROM CAR GROUP BY CAR_PRICE;

SELECT COUNT(CAR_NAME) FROM CAR GROUP BY CAR_PRICE HAVING CAR_PRICE > 120000;

SELECT COUNT(*) "COUNTING" FROM CAR GROUP BY CAR_PRICE HAVING CAR_PRICE > 120000;

CREATE TABLE VISIT(
ENTRY_DATE DATE,
PRICE INT,
DURATION INT
);

INSERT INTO VISIT VALUES
("2023-07-10",1000,20),
("2023-05-01",2000,30),
("2023-05-28",3000,40);

INSERT INTO VISIT VALUES
("2023-06-20",4000,60),
("2023-07-10",5000,30);

SELECT ENTRY_DATE,
COUNT(*) FROM VISIT GROUP BY ENTRY_DATE;

SELECT EXTRACT(YEAR FROM ENTRY_DATE) "YEAR",
EXTRACT(MONTH FROM ENTRY_DATE) "MONTH",
-- ROUND FUN ROUND OF THE DECIMAL POINTS TO 2 DECIMALS
ROUND(AVG(PRICE),2) FROM VISIT
GROUP BY EXTRACT(YEAR FROM ENTRY_DATE),
EXTRACT(MONTH FROM ENTRY_DATE);

SELECT * FROM VISIT;

SELECT ENTRY_DATE, ROUND(AVG(PRICE),3) "AVG_PRICE"
FROM VISIT GROUP BY ENTRY_DATE HAVING
COUNT(*) > 1 ORDER BY ENTRY_DATE;



SELECT * FROM CUSTOMER;

CREATE TABLE EMPLOYEE(
EMP_ID INT, NAME VARCHAR(25),
AGE INT, COUNTRY VARCHAR(20)
);

INSERT INTO EMPLOYEE VALUES
(100,"SWAPNA",23,"INDIA"),
(101,"YAMUNA",39,"AMERICA"),
(102,"SWATHI",40,"US"),
(103,"SAMRIN",34,"US"),
(105,"SUNANDHA",50,"INDIA");

SELECT * FROM EMPLOYEE;

SELECT COUNT(COUNTRY) "COUNTRY_NO", COUNTRY FROM EMPLOYEE GROUP BY
COUNTRY HAVING COUNT(COUNTRY) >= 2;

SELECT COUNTRY
FROM EMPLOYEE GROUP BY
COUNTRY HAVING MAX(AGE) > 30;


CREATE TABLE MANAGER(
ID INT,
NAME VARCHAR(30),
GENDER VARCHAR(20),
SALARY INT);

CREATE TABLE MANAGER1(
ID INT,
NAME VARCHAR(30),
GENDER VARCHAR(20),
AGE INT,
SALARY INT);

-- DROP TABLE MANAGER1;

INSERT INTO MANAGER1 VALUES
(101,"SWAPNA","F",20,100000),
(102,"SWATHI","F",20,200000),
(103,"SWETHA","F",22,400000),
(104,"SUMANTH","M",20,150000),
(105,"RAHUL","M",24,120000);

SELECT * FROM MANAGER1;

SELECT NAME,SUM(SALARY) "TOYAL_SUM" FROM MANAGER1
GROUP BY NAME HAVING SUM(SALARY) > 100000 ORDER BY NAME;

select age from MANAGER1 GROUP BY AGE HAVING COUNT(AGE) > 2;

SELECT GENDER, MAX(SALARY) "MAX_SALARY" FROM MANAGER1
GROUP BY GENDER HAVING MAX(SALARY) < 200000;

SELECT GENDER, MAX(SALARY) "MAX_SALARY" FROM MANAGER1
GROUP BY GENDER HAVING MIN(SALARY) < 200000;


DELIMITER //
CREATE PROCEDURE GetManagerAge()
	BEGIN
		SELECT * FROM MANAGER1 WHERE AGE = 20;
	END //
    
CALL GetManagerAge();


SELECT * FROM MANAGER1;

SELECT NAME FROM MANAGER1 ORDER BY RAND() LIMIT 2;